# The absolute path of the root of the target project
# If none is provided your cwd will be used
project_root:

# The structure of the project
# All paths are relative to the project_root
structure:
  R:
    path: /R/R/
    template: r
    file_extension: .R
  python:
    path: /python/methods/
    template: python
    file_extension: .py
  api:
    path: /src/main/scala/com/example/api/
    template: api
    file_extension: .scala
  implicits:
    path: /src/main/scala/com/example/implicits/
    template: implicits
    file_extension: .scala


# The details of the methods to be templated
# It is recommended that all method names are lowercase with underscores so that the syntax filters can be easily applied
methods:
  sum_columns:
    params:
      df: DataFrame
      col1: String
      col2: String
      newCol: String
    docs: A cool function
    returns: DataFrame
  filter_on_list:
    params:
      df: DataFrame
      targetCol: String
      values: List[Int]
    returns: DataFrame