# The absolute path of the root of the target project
# If none is provided your cwd will be used
project_root:

# The structure of the project
# All paths are relative to the project_root
structure:
  python:
    path: python/methods/
    template: python
    file_name_format: "{}API.py"
  scala:
    path: /test_dir/scala/path/
    template: scala.txt
    file_name_format: "{}.scala"
