language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
jobs:
  include:
  - stage: test
    script: "./scripts/test.sh"
deploy:
  provider: pypi
  user: treilly94
  password:
    secure: oS3a8qHA2uzWwQ2B9fbaj7LZ1BtMDmZoyCGRsAP+ebO7/CjlbJEG8xwZpL7Y5mFkmIXW8dr1o32In0+rwl5+yV462fG5yo9/XShh94M7k++ZI9+EXAKYkusElmL9x7IWJB2eEc4zerlQaMAUUkyl1CC/38IFn7ohZJWqHgJVF6Isp+/rQHYH63c7eKYlm28s6SsvqlcnB71H9GKvaCs6uABAs6tcTIUDZU2LAqOrLpRgpO/kTQZe2ndvniydQaXrKnESOZXVQaxSHkIbmNV0beiTVahCAsN1aWGw8lvwGrPl/1iCipSlAlWXS1tLNzjedSDxaVcxDokqoEJRm5WYXox9H5skJhW3WvPXeRtsNnhLNoEstKrHRitzweq/8vEwhMVuCU+TzlqF//qhaJ9vdq4Kxtt9bgT7tQclR+vJ9XxPMimQKFhSXukIdKmE5CgQT2gJVk8ErwTDRMeEXKSHhXoNHvx2auGg2o8tB6bQ0LTfmGFoAFGkmmhhD5QKZ/mY/gICBIYkt2SQFwMTFVWEotaOwbeNG6MrgPabj9+U4Yz4y49QPoW85KBMXIaWoNRgJRDTd4uM5WPZ57wfqWIjU99kEnuIkkvCuCR0wJDwv/JQasgSDoKkuIGDaUmHdmnwjreDtbH2UZZ8hGcxP26nUV10D9YdIIfz9u276wVkFQA=
  server: https://test.pypi.org/legacy/
  on:
    branch: development
